
Day 2  project: PostgreSQ

-- project   

-- Question 1
-- 1. Retrieve all columns from the customer table.
-- solution_1

select customer_id,
       store_id,
       first_name, 
       last_name,
	   email,
	   address_id,
	   activebool,
	   create_date,
	   last_update,
	   active
	   
from customer;


-- Question 2
-- 2. Display only film_id, title, and rating from the film table.
-- solution_2

select film_id, 
       title, 
	   rating
from film;


-- Question 3
-- 3. Retrieve the first 15 records from the actor table.
-- solution_3

select * 
from actor
fetch first 15 rows only;


-- Question 4
-- 4. Retrieve all customers and sort them by last_name in ascending order.
-- solution_4

select first_name, 
       last_name
from customer
order by last_name asc;

-- Question 5 
-- 5. Display payment_id, customer_id, and amount, sorted by amount from lowest to highest.
-- solution_5

select payment_id, 
       customer_id, 
	   amount
from payment 
order by amount asc; -- 14596 returned

-- Question 6
-- 6. Retrieve customers sorted by:
--     first_name in ascending order
--     last_name in descending order
-- solution_6

select first_name,
       last_name
from customer
order by first_name asc, last_name desc; -- 599 rows returned

-- Question 7
-- 7. Retrieve all payments where the amount is greater than 5.
-- solution_7 

select * from payment
where amount > 5; -- 3618 rows returned

-- Question 8
-- 8. Retrieve all payments where the amount is between 3.99 and 6.99.
-- solution_8

select * from payment
where amount between 3.99 and 6.99; -- 6624 rows returned

-- Question 9
-- 9. Retrieve all customers whose first_name starts with the letter J.
-- solution_9

select first_name, 
        last_name 
from customer
where first_name like 'J%'; -- run successfully and 65 rows affected 

-- Question 10
-- 10. Retrieve all films where the description contains the word “Action”.
-- solution_10

select title, description
from film
where description like '%Action%'; -- 44 rows retuned

-- Question
-- 11. Retrieve payments greater than 7, sorted by amount in descending order.
-- solution_11

select payment_id,
       customer_id,
       staff_id,
       amount,
       payment_date
from payment
where amount > 7
order by amount desc;-- 1000 rows retuned

-- Question 12
-- 12. Retrieve customers whose first name ends with “n”, sorted alphabetically.
-- solution_12

select first_name, last_name
from customer
where first_name like '%n'
order by first_name asc; -- 93 rows returned

-- Question 13
-- 13. Calculate the total amount spent by each customer.
-- solution_13

select customer_id, 
       sum(amount) as total_amount
from payment
group by customer_id
order by total_amount desc; -- 599 rows returned

-- Question 14
-- 14. Retrieve the average payment amount per customer.
-- solution_14
select customer_id, 
       avg(amount) as avg_amount
from payment
group by customer_id
order by avg_amount; -- 599 rows returned

-- Question 15
-- 15. Calculate the total revenue generated by each staff member.
-- solution_15

select staff_Id,
       sum(amount) as total_revenue
from payment
group by staff_id
order by total_revenue; -- 2 rows returned

-- question 16 
-- 16. Identify the top 5 customers based on total payment amount.
-- solution_16

select customer_id, 
	   sum(amount) as total_payment
from payment
group by customer_id
order by total_payment desc
limit 5;  -- 5 rows returned

-- Question 17
-- 17. Find the average film length per release year.
-- solution_17

select  release_year,
	   avg(length) as avg_length
from film
group by release_year; -- 1 rows returned

-- Question 18
-- 18. Retrieve the highest single payment amount in the payment table.
-- solution_18

select max(amount) as highest_payment
from payment; -- 1 row returned the highest single payment amount is 11.99

-- Question 19
-- 19. Count how many payments each customer has made.
-- solution_19

select customer_id,
       count(payment_id) as  payment_count
from payment
group by customer_id
order by payment_count; -- 599 rows returned

-- Question 20
-- 20. Retrieve customers who are active and sort them by first_name.
-- solution_20

select first_name, 
       last_name
from customer
where active = 1
order by first_name; -- we have 584 active customers







